name: scrumlab_flutter_qr_bar_scanner_example
description: Demonstrates how to use the scrumlab_flutter_qr_bar_scanner plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  scrumlab_flutter_qr_bar_scanner:
    path: ../

flutter:
  uses-material-design: true